stages:
  - test
  - deploy

before_script:
  - nodejs -v
  - npm -v
  - pwd
  - npm install
  - mocha -v || sudo npm install -g mocha
  - sudo apt-get install -y mongodb
  - sudo service mongodb start

rspec:
  stage: test
  script:
    - mocha tests
