before_script:
  - sudo apt-get update -qq && sudo apt-get install -y nodejs nodejs-legacy npm mongodb
  - sudo service mongod start
  - nodejs -v
  - npm -v
  - npm install

rspec:
  script:
    - mocha tests
